---
# created by Andrei Lupuleasa, December 2018.
- name: 1.Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    state: present
    update_cache: yes
    cache_valid_time: 86400 #One day
  tags: daily

- name: 2.Install programs
  apt: 
    pkg:
     - curl
     - ftp
     - gcc
     - git
     - man
     - unzip
     - vim
     - wget
     - zip  
     - composer
     - htop
    state: present
    update_cache: yes
    cache_valid_time: 86400 #One day
  tags: daily
    
- name: 3.Install python extensions
  apt: name=python-pexpect update_cache=yes state=latest cache_valid_time=86400 #One day
  tags: daily
  ignore_errors: yes

- name: 4.Install vim settings
  git:
    repo: https://github.com/alupuleasa/vimrc.git
    version: master
    dest: /home/vagrant/.vimrc
  become: no
  tags: once

- name: 5.Install vim color schemes
  git:
    repo: https://github.com/alupuleasa/vim-colorschemes.git
    version: master
    dest: /home/vagrant/.vim
  become: no
  tags: once

- name: 6.Modify Bashrc HISTSIZE.
  lineinfile:
    path: /home/vagrant/.bashrc
    regexp: 'HISTSIZE=1000'
    line: 'HISTSIZE='
  tags: once

- name: 7.Modify Bashrc HISTSIZE.
  lineinfile:
    path: /home/vagrant/.bashrc
    regexp: 'HISTFILESIZE=2000'
    line: 'HISTFILESIZE='
  tags: once

#git@github.com:alupuleasa/vimrc.git
#https://github.com/alupuleasa/vimrc.git

#https://github.com/flazz/vim-colorschemes.git
#git@github.com:alupuleasa/vimrc.git

# - name: 4.Clone Vimrc
#   git:
#     repo: git@github.com:alupuleasa/vimrc.git
#     version: master
#     dest: /var/www/html/vimrc
#     accept_hostkey: yes
#   # ssh-agent doesn't allow key to pass through remote sudo commands.
#   become: no
#   notify:
#     - move-vimrc

# - name: 1.Change key permission
#   become: true
#   file: 
#     path: /home/vagrant/.ssh/id_rsa
#     mode: 0400

# How to add .bashrc variable
# export test="xxx"
# sed -i 's/HISTSIZE=1000/HISTSIZE=/g' ~/.bashrc
# sed -i 's/HISTFILESIZE=2000/HISTFILESIZE=/g' ~/.bashrc

# - name: 4.Copy Vimrc
#   copy: 
#     src: .vimrc
#     dest: /home/vagrant/.vimrc
#   tags: once