---
- name: 1.Transfer shell script
  copy: src: install_go1.19.sh dest=~/install_go1.19.sh mode=0777
  tags: once

- name: 2.Execute shell script
  become: true
  command: sh install_go1.19.sh
  tags: once